DEFAULT_PROCESS_STEPS = [("Brightness", 1.4), ("Contrast", 1.9), ("Sharpness", 1.7)]

ROTATE_GAUSSIAN_BLUR_SIZE = (51, 51)
SMOOTH_GAUSSIAN_BLUR_SIZE = (21, 5)
IMAGE_MAGICK_CMD = "convert"
UNPAPER_CMD = "unpaper"
DENSITY = 300
RESIZE_WIDTH = 2481
RESIZE_HEIGHT = 3507
DEPTH = 8
COLORSPACE = "Gray"
SHARPEN_FACTOR = "0x2.7"
BLACK_THRESHOLD_PERCENT = "35%"
WHITE_THRESHOLD_PERCENT = "75%"
UNPAPER_BLACK_THRESHOLD = 0.1
UNPAPER_NI = 8

STANDARD_WIDTH = 2481
