import numpy as np

CANNY_THRESHOLD_LOW = 50
CANNY_THRESHOLD_HIGH = 150

GAUSSIAN_BLUR_SIZE = (9, 9)

HOUGH_LINES_RHO = 1
HOUGH_LINES_THETA = np.pi / 180
HOUGH_LINES_THRESHOLD = 100
HOUGH_LINES_MIN_LENGTH = 100
HOUGH_LINES_MAX_GAP = 10

ANGLE_TOLERANCE = 10
WIDTH_RATIO = 1 / 3

CONTOUR_AREA_THRESHOLD = 100
NUM_LARGEST_CONTOURS = 1
