# Generated by Django 5.0.6 on 2024-06-04 17:01

import django.contrib.postgres.fields
import django.db.models.deletion
import functools
import ocr.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageFilterFactor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.CharField(default=ocr.models.generate_uid, editable=False, max_length=36, unique=True)),
                ("contrast", models.FloatField(default=1.0)),
                ("brightness", models.FloatField(default=1.0)),
                ("sharpness", models.FloatField(default=1.0)),
                (
                    "filter_order",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("brightness", "Brightness"),
                                ("contrast", "Contrast"),
                                ("sharpness", "Sharpness"),
                            ],
                            max_length=32,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                ("slug", models.CharField(editable=False, max_length=80, null=True, unique=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="OcrBoxImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.CharField(default=ocr.models.generate_uid, editable=False, max_length=36, unique=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to=functools.partial(
                            ocr.models._get_image_upload_path,
                            *(),
                            **{"base_path": "ocr_box_images", "hash_field": "image_md5"}
                        )
                    ),
                ),
                (
                    "resized_image",
                    models.ImageField(
                        null=True,
                        upload_to=functools.partial(
                            ocr.models._get_image_upload_path,
                            *(),
                            **{"base_path": "ocr_box_images_resized", "hash_field": "image_md5"}
                        ),
                    ),
                ),
                ("resized_image_width", models.IntegerField(null=True)),
                ("resized_image_height", models.IntegerField(null=True)),
                ("image_md5", models.CharField(editable=False, max_length=32, null=True)),
                ("level", models.IntegerField()),
                ("page_num", models.IntegerField()),
                ("block_num", models.IntegerField()),
                ("par_num", models.IntegerField()),
                ("line_num", models.IntegerField()),
                ("word_num", models.IntegerField()),
                ("left", models.IntegerField()),
                ("top", models.IntegerField()),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("is_line", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image_filter_factor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_box_images",
                        to="ocr.imagefilterfactor",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalOcrBoxText",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "uid",
                    models.CharField(db_index=True, default=ocr.models.generate_uid, editable=False, max_length=36),
                ),
                ("text", models.TextField()),
                ("md5_hash", models.CharField(editable=False, max_length=32, null=True)),
                ("is_cleaned", models.BooleanField(default=False)),
                ("extraction_config_context", models.JSONField(blank=True, null=True)),
                (
                    "extraction_method",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Unknown"),
                            (1, "Tesseract"),
                            (2, "Ocrmypdf"),
                            (3, "Abbyy"),
                            (4, "Easy Ocr"),
                            (5, "Ocr Layer Grab"),
                            (6, "Text Grab"),
                            (7, "Apple Ocr"),
                        ],
                        default=1,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image_filter_factor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ocr.imagefilterfactor",
                    ),
                ),
                (
                    "ocr_box_image",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ocr.ocrboximage",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical ocr box text",
                "verbose_name_plural": "historical ocr box texts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="OcrPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.CharField(default=ocr.models.generate_uid, editable=False, max_length=36, unique=True)),
                ("page_index", models.IntegerField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to=functools.partial(
                            ocr.models._get_image_upload_path,
                            *(),
                            **{"base_path": "ocr_images", "hash_field": "image_md5"}
                        )
                    ),
                ),
                ("image_md5", models.CharField(editable=False, max_length=32, null=True, unique=True)),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image_filter_factor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_pages",
                        to="ocr.imagefilterfactor",
                    ),
                ),
                (
                    "orig_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="child_pages",
                        to="ocr.ocrpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="ocrboximage",
            name="ocr_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="ocr_box_images", to="ocr.ocrpage"
            ),
        ),
        migrations.CreateModel(
            name="HistoricalOcrPageText",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "uid",
                    models.CharField(db_index=True, default=ocr.models.generate_uid, editable=False, max_length=36),
                ),
                ("text", models.TextField()),
                ("md5_hash", models.CharField(editable=False, max_length=32, null=True)),
                ("is_cleaned", models.BooleanField(default=False)),
                ("extraction_config_context", models.JSONField(blank=True, null=True)),
                (
                    "extraction_method",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Unknown"),
                            (1, "Tesseract"),
                            (2, "Ocrmypdf"),
                            (3, "Abbyy"),
                            (4, "Easy Ocr"),
                            (5, "Ocr Layer Grab"),
                            (6, "Text Grab"),
                            (7, "Apple Ocr"),
                        ],
                        default=0,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image_filter_factor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ocr.imagefilterfactor",
                    ),
                ),
                (
                    "ocr_page",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ocr.ocrpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical ocr page text",
                "verbose_name_plural": "historical ocr page texts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="OcrProject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.CharField(default=ocr.models.generate_uid, editable=False, max_length=36, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Created"),
                            (1, "Processed"),
                            (2, "Error"),
                            (10, "Image Processing"),
                            (20, "Text Processing"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Scan Layout One Page"),
                            (2, "Scan Layout Two Pages"),
                            (3, "Camera Shot"),
                        ],
                        default=0,
                    ),
                ),
                ("pdf_file", models.FileField(blank=True, null=True, upload_to="ocr_projects")),
                ("pdf_file_md5", models.CharField(editable=False, max_length=32, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "orig_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="child_projects",
                        to="ocr.ocrproject",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="ocrpage",
            name="ocr_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ocr_pages",
                to="ocr.ocrproject",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalOcrProject",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "uid",
                    models.CharField(db_index=True, default=ocr.models.generate_uid, editable=False, max_length=36),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Created"),
                            (1, "Processed"),
                            (2, "Error"),
                            (10, "Image Processing"),
                            (20, "Text Processing"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Scan Layout One Page"),
                            (2, "Scan Layout Two Pages"),
                            (3, "Camera Shot"),
                        ],
                        default=0,
                    ),
                ),
                ("pdf_file", models.TextField(blank=True, max_length=100, null=True)),
                ("pdf_file_md5", models.CharField(db_index=True, editable=False, max_length=32, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "orig_project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ocr.ocrproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical ocr project",
                "verbose_name_plural": "historical ocr projects",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="OcrBoxText",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.CharField(default=ocr.models.generate_uid, editable=False, max_length=36, unique=True)),
                ("text", models.TextField()),
                ("md5_hash", models.CharField(editable=False, max_length=32, null=True)),
                ("is_cleaned", models.BooleanField(default=False)),
                ("extraction_config_context", models.JSONField(blank=True, null=True)),
                (
                    "extraction_method",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Unknown"),
                            (1, "Tesseract"),
                            (2, "Ocrmypdf"),
                            (3, "Abbyy"),
                            (4, "Easy Ocr"),
                            (5, "Ocr Layer Grab"),
                            (6, "Text Grab"),
                            (7, "Apple Ocr"),
                        ],
                        default=1,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image_filter_factor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_box_texts",
                        to="ocr.imagefilterfactor",
                    ),
                ),
                (
                    "ocr_box_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ocr_box_texts", to="ocr.ocrboximage"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "unique_together": {("ocr_box_image", "md5_hash")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="ocrboximage",
            unique_together={("ocr_page", "image_md5")},
        ),
        migrations.CreateModel(
            name="OcrPageText",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.CharField(default=ocr.models.generate_uid, editable=False, max_length=36, unique=True)),
                ("text", models.TextField()),
                ("md5_hash", models.CharField(editable=False, max_length=32, null=True)),
                ("is_cleaned", models.BooleanField(default=False)),
                ("extraction_config_context", models.JSONField(blank=True, null=True)),
                (
                    "extraction_method",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Unknown"),
                            (1, "Tesseract"),
                            (2, "Ocrmypdf"),
                            (3, "Abbyy"),
                            (4, "Easy Ocr"),
                            (5, "Ocr Layer Grab"),
                            (6, "Text Grab"),
                            (7, "Apple Ocr"),
                        ],
                        default=0,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image_filter_factor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_page_texts",
                        to="ocr.imagefilterfactor",
                    ),
                ),
                (
                    "ocr_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ocr_page_texts", to="ocr.ocrpage"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "unique_together": {("ocr_page", "md5_hash")},
            },
        ),
    ]
