# Generated by Django 5.0.6 on 2024-06-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalocrboxtext",
            name="confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ocrboxtext",
            name="confidence",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
